# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    build:
      context: ./db/
      dockerfile: Dockerfile
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=senacgrupo1
      - MYSQL_DATABASE=sideschooldb
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    networks:
      - spring-boot-mysql-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/sideschooldb?autoReconnect=true&useSSL=false
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge